- name: Download angelscript_{{ psplibraries_angelscript_version }}
  get_url:
    url: http://www.angelcode.com/angelscript/sdk/files/angelscript_{{ psplibraries_angelscript_version }}.zip
    dest: "{{ psplibraries_tmp_path }}"
    sha256sum: 667e5238c1ec687df8e5b6888871855a50d892a548970680f6c8556f19023e0c

- name: Extract angelscript_{{ psplibraries_angelscript_version }}
  unarchive:
    src: "{{ psplibraries_tmp_path }}/angelscript_{{ psplibraries_angelscript_version }}.zip"
    dest: "{{ psplibraries_tmp_path }}"
    copy: no
    creates: "{{ psplibraries_tmp_path }}/sdk/angelscript/source/as_generic.cpp"

- name: Configure angelscript_{{ psplibraries_angelscript_version }}
  shell: . /etc/profile; psp-cmake -D CMAKE_INSTALL_PREFIX={{ psp_prefix }} .
  args:
    chdir: "{{ psplibraries_tmp_path }}/sdk/angelscript/projects/cmake"
    creates: "{{ psplibraries_tmp_path }}/sdk/angelscript/projects/cmake/Makefile"

- name: Compile angelscript_{{ psplibraries_angelscript_version }}
  shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/sdk/angelscript/projects/cmake"
    creates: "{{ psplibraries_tmp_path }}/sdk/angelscript/lib/libAngelscript.a"

- name: Install angelscript_{{ psplibraries_angelscript_version }} header and library
  sudo: yes
  command: "cp {{ item.path }}/{{ item.file }} {{ psp_prefix }}/{{ item.path }}"
  args:
    chdir: "{{ psplibraries_tmp_path }}/sdk/angelscript/"
    creates: "{{ psp_prefix }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { file: 'angelscript.h', path: 'include/' }
    - { file: 'libAngelscript.a', path: 'lib/' }
