- name: Download bzip2-{{ psplibraries_bzip2_version }}
  get_url:
    url: http://www.bzip.org/{{ psplibraries_bzip2_version }}/bzip2-{{ psplibraries_bzip2_version }}.tar.gz
    dest: "{{ psplibraries_tmp_path }}"
    sha256sum: a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd

- name: Extract bzip2-{{ psplibraries_bzip2_version }}
  unarchive:
    src: "{{ psplibraries_tmp_path }}/bzip2-{{ psplibraries_bzip2_version }}.tar.gz"
    dest: "{{ psplibraries_tmp_path }}"
    copy: no
    creates: "{{ psplibraries_tmp_path }}/bzip2-{{ psplibraries_bzip2_version }}/bzip2.c"

- name: Apply bzip2-{{ psplibraries_bzip2_version }}-PSP patch
  patch:
    src: bzip2-{{ psplibraries_bzip2_version }}-PSP.patch
    basedir: "{{ psplibraries_tmp_path }}/bzip2-{{ psplibraries_bzip2_version }}"
    strip: 1

- name: Compile bzip2-{{ psplibraries_bzip2_version }}
  shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/bzip2-{{ psplibraries_bzip2_version }}"
    creates: "{{ psplibraries_tmp_path }}/bzip2-{{ psplibraries_bzip2_version }}/libbz2.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install bzip2-{{ psplibraries_bzip2_version }}
  sudo: yes
  shell: make -j {{ ansible_processor_vcpus }} install
  args:
    chdir: "{{ psplibraries_tmp_path }}/bzip2-{{ psplibraries_bzip2_version }}"
    creates: "{{ psp_prefix }}/lib/libbz2.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
