- name: Download expat-{{ psplibraries_expat_version }}
  get_url:
    url=http://sourceforge.net/projects/expat/files/expat/{{ psplibraries_expat_version }}/expat-{{ psplibraries_expat_version }}.tar.gz
    dest={{ psplibraries_tmp_path }}

- name: Extract expat-{{ psplibraries_expat_version }}
  unarchive:
    src={{ psplibraries_tmp_path }}/expat-{{ psplibraries_expat_version }}.tar.gz
    dest={{ psplibraries_tmp_path }}
    copy=no

- name: Copy config.sub file
  copy:
    src=config.sub
    dest={{ psplibraries_tmp_path }}//expat-{{ psplibraries_expat_version }}/{{ item }}
  with_items:
    - config.sub
    - conftools/config.sub

- name: Configure expat-{{ psplibraries_expat_version }}
  shell: chdir={{ psplibraries_tmp_path }}/expat-{{ psplibraries_expat_version }} ./configure --host={{ target }} --prefix={{ pspdev_path }}
  environment:
    LDFLAGS: -L{{ pspsdk_path }}/lib -L{{ psp_prefix }}/lib -lc -lpspuser
    LIBS: -lc -lpspuser
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Compile expat-{{ psplibraries_expat_version }}
  shell: make -j {{ ansible_processor_vcpus }}
    chdir={{ psplibraries_tmp_path }}/sdk/angelscript/projects/cmake
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install expat-{{ psplibraries_expat_version }}
  sudo: yes
  shell: chdir={{ psplibraries_tmp_path }}/expat-{{ psplibraries_expat_version }} make -j {{ ansible_processor_vcpus }} install; make clean
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Clean expat-{{ psplibraries_expat_version }}
  file:
    path={{ psplibraries_tmp_path }}/expat-{{ psplibraries_expat_version }}
    state=absent
