- name: Download libyaml-{{ psplibraries_libyaml_version }}
  get_url:
    url: http://pyyaml.org/download/libyaml/yaml-{{ psplibraries_libyaml_version }}.tar.gz
    dest: "{{ psplibraries_tmp_path }}"
    sha256sum: 7bf81554ae5ab2d9b6977da398ea789722e0db75b86bffdaeb4e66d961de6a37

- name: Extract libyaml-{{ psplibraries_libyaml_version }}
  unarchive:
    src: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}.tar.gz"
    dest: "{{ psplibraries_tmp_path }}"
    copy: no
    creates: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}/Makefile.in"

- name: Copy config.sub file
  copy:
    src: config.sub
    dest: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}/config/config.sub"

- name: Configure libyaml-{{ psplibraries_libyaml_version }}
  shell: ./configure --host={{ target }} --prefix={{ pspdev_path }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}"
    creates: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}/Makefile"
  environment:
    LDFLAGS: -L{{ pspsdk_path }}/lib -L{{ psp_prefix }}/lib -lc -lpspuser
    LIBS: -lc -lpspuser
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Compile libyaml-{{ psplibraries_libyaml_version }}
  shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}"
    creates: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}/src/libyaml.la"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install libyaml-{{ psplibraries_libyaml_version }}
  sudo: yes
  shell: make -j {{ ansible_processor_vcpus }} install
  args:
    chdir: "{{ psplibraries_tmp_path }}/yaml-{{ psplibraries_libyaml_version }}"
    creates: "{{ pspdev_path }}/lib/libyaml.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
