- name: Download openal-{{ psplibraries_openal_version }}
  get_url:
    url: http://kcat.strangesoft.net/openal-releases/openal-soft-{{ psplibraries_openal_version }}.tar.bz2
    dest: "{{ psplibraries_tmp_path }}"
    sha256sum: 87bd8d61d5943387898c92b6a2bbbb26118e745dec57550c817526a70fad0914

- name: Extract openal-{{ psplibraries_openal_version }}
  unarchive:
    src: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}.tar.bz2"
    dest: "{{ psplibraries_tmp_path }}"
    copy: no
    creates: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}/config.h.in"

- name: Configure openal-{{ psplibraries_openal_version }}
  shell: . /etc/profile; psp-cmake -D CMAKE_INSTALL_PREFIX={{ psp_prefix }} -D UTILS=OFF .
  args:
    chdir: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}"
    creates: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}/Makefile"

- name: Replace memory.h with string.h
  shell: sed -i -e "s/memory\.h/string.h/" Alc/*.c Alc/backends/*.c
  args:
    chdir: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}"

- name: Compile openal-{{ psplibraries_openal_version }}
  shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}"
    creates: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}/libopenal.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install openal-{{ psplibraries_openal_version }}
  sudo: yes
  shell: make -j {{ ansible_processor_vcpus }} install
  args:
    chdir: "{{ psplibraries_tmp_path }}/openal-soft-{{ psplibraries_openal_version }}"
    creates: "{{ psp_prefix }}/lib/libopenal.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
