- name: Download pixman-{{ psplibraries_pixman_version }}
  get_url:
    url=http://cairographics.org/releases/pixman-{{ psplibraries_pixman_version }}.tar.gz
    dest={{ psplibraries_tmp_path }}

- name: Extract pixman-{{ psplibraries_pixman_version }}
  unarchive:
    src={{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}.tar.gz
    dest={{ psplibraries_tmp_path }}
    copy=no

- name: Copy config.sub file
  copy:
    src=config.sub
    dest={{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}/config.sub

- name: Configure pixman-{{ psplibraries_pixman_version }}
  shell: ./configure --host={{ target }} --prefix={{ pspdev_path }}
    chdir={{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}
  environment:
    LDFLAGS: -L{{ pspsdk_path }}/lib -L{{ psp_prefix }}/lib -lc -lpspuser
    LIBS: -lc -lpspuser
    PNG_CFLAGS: -I{{ psp_prefix }}/include
    PNG_LIBS: -L{{ psp_prefix }}/lib -lpng -lz
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Compile pixman-{{ psplibraries_pixman_version }}
  shell: make -j {{ ansible_processor_vcpus }}
    chdir={{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install pixman-{{ psplibraries_pixman_version }}
  sudo: yes
  shell: chdir={{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }} make -j {{ ansible_processor_vcpus }} install; make clean
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Clean pixman-{{ psplibraries_pixman_version }}
  file:
    path={{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}
    state=absent
