- name: Download pixman-{{ psplibraries_pixman_version }}
  get_url:
    url: http://cairographics.org/releases/pixman-{{ psplibraries_pixman_version }}.tar.gz
    dest: "{{ psplibraries_tmp_path }}"
    sha256sum: fea7869c2ba41f49fbe1c9382390ff671ac62add44dc5f29134e61d0f17960de

- name: Extract pixman-{{ psplibraries_pixman_version }}
  unarchive:
    src: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}.tar.gz"
    dest: "{{ psplibraries_tmp_path }}"
    copy: no
    creates: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}/Makefile.in"

- name: Copy config.sub file
  copy:
    src: config.sub
    dest: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}/config.sub"

- name: Configure pixman-{{ psplibraries_pixman_version }}
  shell: ./configure --host={{ target }} --prefix={{ pspdev_path }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}"
    creates: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}/Makefile"
  environment:
    LDFLAGS: -L{{ pspsdk_path }}/lib -L{{ psp_prefix }}/lib -lc -lpspuser
    LIBS: -lc -lpspuser
    PNG_CFLAGS: -I{{ psp_prefix }}/include
    PNG_LIBS: -L{{ psp_prefix }}/lib -lpng -lz
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Compile pixman-{{ psplibraries_pixman_version }}
  shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}"
    creates: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}/pixman/.libs/libpixman-1.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install pixman-{{ psplibraries_pixman_version }}
  sudo: yes
  shell: make -j {{ ansible_processor_vcpus }} install
  args:
    chdir: "{{ psplibraries_tmp_path }}/pixman-{{ psplibraries_pixman_version }}"
    creates: "{{ pspdev_path }}/lib/libpixman-1.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
