- name: Download pthreads-emb
  git: repo=git://github.com/take-cheeze/pthreads-emb
       dest={{ psplibraries_tmp_path }}/pthreads-emb
       accept_hostkey=yes

- name: Compile pthreads-emb
  shell: make -C platform/psp -j {{ ansible_processor_vcpus }}
    chdir={{ psplibraries_tmp_path }}/pthreads-emb
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install pthreads-emb
  sudo: yes
  shell: make -C platform/psp install
    chdir={{ psplibraries_tmp_path }}/pthreads-emb
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install pthreads-emb headers
  sudo: yes
  command: cp {{ psplibraries_tmp_path }}/pthreads-emb/{{ item }} {{ psp_prefix }}/include
  with_items:
    - 'implement.h'
    - 'need_errno.h'
    - 'pte_generic_osal.h'
    - 'pthread.h'
    - 'sched.h'
    - 'semaphore.h'
