- name: Download smpeg-psp
  git:
    repo: git://github.com/fungos/smpeg-psp
    dest: "{{ psplibraries_tmp_path }}/smpeg-psp"
    accept_hostkey: yes
    force: yes

- name: Disable_SDL_Swap16
  shell: sed -i -e "s/static __inline__ Uint16 SDL_Swap16(Uint16 x)/static __inline__ Uint16 Disable_SDL_Swap16(Uint16 x)/" audio/*.cpp
  args:
    chdir: "{{ psplibraries_tmp_path }}/smpeg-psp"

- name: Compile smpeg-psp
  shell: make -j {{ ansible_processor_vcpus }}
  args:
    chdir: "{{ psplibraries_tmp_path }}/smpeg-psp"
    creates: "{{ psplibraries_tmp_path }}/smpeg-psp/libsmpeg.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install smpeg-psp
  sudo: yes
  shell: make install
  args:
    chdir: "{{ psplibraries_tmp_path }}/smpeg-psp"
    creates: "{{ psp_prefix }}/lib/libsmpeg.a"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
